// packages/ui/src/lib/components/ui/Switch.tsx
interface SwitchProps {
  checked: boolean;
  onChange: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
}

export function Switch({ checked, onChange, label, disabled = false }: SwitchProps) {
  return (
    <label className="flex items-center gap-2 cursor-pointer select-none">
      <button
        role="switch"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={`relative w-9 h-5 rounded-full transition-colors duration-200 ${
          checked ? "bg-nova-accent" : "bg-slate-700"
        } ${disabled ? "opacity-50 cursor-not-allowed" : ""}`}
      >
        <span
          className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white transition-transform duration-200 ${
            checked ? "translate-x-4" : "translate-x-0"
          }`}
        />
      </button>
      {label && <span className="text-xs text-slate-300">{label}</span>}
    </label>
  );
}

// packages/ui/src/lib/components/ui/Switch.svelte
<script lang="ts">
  let {
    checked = false,
    disabled = false,
    onchange,
    label = "",
    id = "",
  }: {
    checked?: boolean;
    disabled?: boolean;
    onchange?: (e: Event) => void;
    label?: string;
    id?: string;
  } = $props();

  let switchId = $state("");
  $effect(() => {
    switchId = id || "switch-" + Math.random().toString(36).slice(2, 9);
  });
</script>

<div class="flex items-center gap-2">
  <button
    role="switch"
    aria-checked={checked}
    aria-label={label}
    id={switchId}
    {disabled}
    {onchange}
    class="relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:shadow-[0_0_0_2px_rgba(45,212,191,0.3)]
      {checked ? 'bg-nova-accent' : 'bg-[#1a3a3a]'}
      {disabled ? 'opacity-50 cursor-not-allowed' : ''}"
  >
    <span
      class="pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow-sm ring-0 transition duration-200 ease-in-out
        {checked ? 'translate-x-4' : 'translate-x-0'}"
    ></span>
  </button>
  {#if label}
    <label for={switchId} class="text-sm text-nova-foreground cursor-pointer select-none">{label}</label>
  {/if}
</div>
